export const textRecords = [
  'avatar',
  'description',
  'email',
  'keywords',
  'notice',
  'url',
  'com.discord',
  'com.github',
  'com.reddit',
  'com.twitter',
  'eth.farcaster',
  'eth.ens.delegate',
  'org.telegram',
] as const
