import { Basic } from "@app/layouts/Basic";
import { Box, Typography } from "@ensdomains/thorin";
import type { NextPage } from "next";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import styled from "styled-components";

const GradientTitle = styled.h1`
  font-size: var(--fontSizes-headingOne);
  font-weight: 800;
  background-image: var(--mode-gradients-accent);
  background-repeat: no-repeat;
  background-size: 110%;
  background-clip: text;
  color: transparent;
  margin-bottom: var(--space-3);
`;

const SubtitleWrapper = styled(Box)`
  max-width: calc(var(--space-72) * 2);
  text-align: center;
`;

const Home: NextPage = () => {
  const { t } = useTranslation("common");

  return (
    <Basic>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        flexGrow={1}
        display="flex"
        flexDirection="column"
        justifyContent="center"
        alignItems="center"
      >
        <GradientTitle>{t("title")}</GradientTitle>
        <SubtitleWrapper>
          <Typography size="large" color="textSecondary">
            {t("description")}
          </Typography>
        </SubtitleWrapper>
      </Box>
    </Basic>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale)),
      // Will be passed to the page component as props
    },
  };
}

export default Home;
