# File: .github/workflows/storycheck-example.yml
name: StoryCheck Example - ENS Registration Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pnpm # Setup pnpm to use the ENS dApp specificed packageManager version in package.json
        uses: pnpm/action-setup@v4
      - name: Run StoryCheck
        id: storycheck      
        uses: GuardianUI/storycheck@v0.1.9
        env: 
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}        
        with:
          storypath: 'user-stories/ens_reg_commit'
      - name: Check if passed
        if: ${{ steps.storycheck.outputs.passed != 'true' }}
        run: echo "StoryCheck failed!" && exit 1